server:
  port: 8081
spring:
  application:
    name: hibernate
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_t?characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update